name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://lioncat6.com/
        drop-html-extension: true

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Verify if sitemap was changed
      id: verify-changes
      uses: tj-actions/verify-changed-files@v20
      with:
        files: ${{ steps.sitemap.outputs.sitemap-path }}

    - name: Commit and push sitemap
      if: steps.verify-changes.outputs.files_changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ${{ steps.sitemap.outputs.sitemap-path }}
        git commit -m "Automated sitemap update."
        git push origin main
